name: Manual .Net Build

on:
  workflow_dispatch

jobs:
  print-runtime-context:
    runs-on: ubuntu-latest

    steps:
      - name: Start build process
        run: echo "Build process has started..."

      - name: Show runtime context
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow}}"
          echo "Triggered by: ${{ github.event_name }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Run number: ${{ github.run_number}}"
          echo " 🍃 Branch: ${{ github.ref }}"

  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install .NET 9
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: "9.0.x"
          
      - name: Build project
        run: dotnet build CleanCodeCodeAlongs\GitWorkflows\GitWorkflows.csproj

      - name: Run code
        run: dotnet run --project CleanCodeCodeAlongs\GitWorkflows\GitWorkflows.csproj
          
