name: .NET CI MIXED

on: 
    workflow_dispatch: {}
    push:
        branches: [main]
        paths:
            - "**/*.cs"
    pull_request:
        branches:
            [main]
        paths:
            - "**/*.cs"


jobs:
  minsta_job_id:
    runs-on: ubuntu-latest
    steps:
        - run: echo "HEJ"


    
  